bounds:
  weight_factor.LIF_exc.l4_i: !!python/tuple
    - 0.2
    - 5.
  weight_factor.LIF_inh.l4_i: !!python/tuple
    - 0.2
    - 5.
  weight_factor.Nr5a1.l4_i: !!python/tuple
    - 0.2
    - 5.
  weight_factor.PV1.l4_i: !!python/tuple
    - 0.2
    - 5.
  weight_factor.PV2.l4_i: !!python/tuple
    - 0.2
    - 5.
  weight_factor.Rorb.l4_i: !!python/tuple
    - 0.2
    - 5.
  weight_factor.Scnn1a.l4_i: !!python/tuple
    - 0.2
    - 5.
  weight_factor.LIF_exc.l4_e: !!python/tuple
    - 0.2
    - 5.
  weight_factor.LIF_inh.l4_e: !!python/tuple
    - 0.2
    - 5.
  weight_factor.Nr5a1.l4_e: !!python/tuple
    - 0.2
    - 5.
  weight_factor.PV1.l4_e: !!python/tuple
    - 0.2
    - 5.
  weight_factor.PV2.l4_e: !!python/tuple
    - 0.2
    - 5.
  weight_factor.Rorb.l4_e: !!python/tuple
    - 0.2
    - 5.
  weight_factor.Scnn1a.l4_e: !!python/tuple
    - 0.2
    - 5.
rel_bounds:
feature_names:
- spont_rate.LIF_exc
- spont_rate.LIF_inh
- spont_rate.Nr5a1
- spont_rate.PV1
- spont_rate.PV2
- spont_rate.Rorb
- spont_rate.Scnn1a
- grating_pref_rate.LIF_exc
- grating_ortho_rate.LIF_exc
- grating_rate.LIF_inh
- grating_pref_rate.Nr5a1
- grating_ortho_rate.Nr5a1
- grating_rate.PV1
- grating_rate.PV2
- grating_pref_rate.Rorb
- grating_ortho_rate.Rorb
- grating_pref_rate.Scnn1a
- grating_ortho_rate.Scnn1a
update_context:
- - optimize_L4_bionet
  - update_context
get_features_stages:
- source: optimize_L4_bionet
  compute_features: compute_features
get_objectives:
  optimize_L4_bionet: get_objectives
kwargs:
  verbose: 2
  bionet_config_file_path: config.json
  grating_angle: 0.
  pop_categories:
    l4_i:
      - LIF_inh
      - PV1
      - PV2
    l4_e:
      - LIF_exc
      - Nr5a1
      - Rorb
      - Scnn1a
    ext:
      - tw
      - lgn
  export_connections: False
objective_names:
- spont_rate.LIF_exc
- spont_rate.LIF_inh
- spont_rate.Nr5a1
- spont_rate.PV1
- spont_rate.PV2
- spont_rate.Rorb
- spont_rate.Scnn1a
- grating_pref_rate.LIF_exc
- grating_ortho_rate.LIF_exc
- grating_rate.LIF_inh
- grating_pref_rate.Nr5a1
- grating_ortho_rate.Nr5a1
- grating_rate.PV1
- grating_rate.PV2
- grating_pref_rate.Rorb
- grating_ortho_rate.Rorb
- grating_pref_rate.Scnn1a
- grating_ortho_rate.Scnn1a
optimization_title: L4_bionet
param_gen: PopulationAnnealing
param_names:
- weight_factor.LIF_exc.l4_i
- weight_factor.LIF_inh.l4_i
- weight_factor.Nr5a1.l4_i
- weight_factor.PV1.l4_i
- weight_factor.PV2.l4_i
- weight_factor.Rorb.l4_i
- weight_factor.Scnn1a.l4_i
- weight_factor.LIF_exc.l4_e
- weight_factor.LIF_inh.l4_e
- weight_factor.Nr5a1.l4_e
- weight_factor.PV1.l4_e
- weight_factor.PV2.l4_e
- weight_factor.Rorb.l4_e
- weight_factor.Scnn1a.l4_e
target_range:
  spont_rate.LIF_exc: 0.05
  spont_rate.LIF_inh: 0.05
  spont_rate.Nr5a1: 0.05
  spont_rate.PV1: 0.05
  spont_rate.PV2: 0.05
  spont_rate.Rorb: 0.05
  spont_rate.Scnn1a: 0.05
  grating_pref_rate.LIF_exc: 0.05
  grating_ortho_rate.LIF_exc: 0.05
  grating_rate.LIF_inh: 0.05
  grating_pref_rate.Nr5a1: 0.05
  grating_ortho_rate.Nr5a1: 0.05
  grating_rate.PV1: 0.05
  grating_rate.PV2: 0.05
  grating_pref_rate.Rorb: 0.05
  grating_ortho_rate.Rorb: 0.05
  grating_pref_rate.Scnn1a: 0.05
  grating_ortho_rate.Scnn1a: 0.05
target_val:
  spont_rate.LIF_exc: 3.0010052631578943
  spont_rate.LIF_inh: 2.506888235294118
  spont_rate.Nr5a1: 3.0010052631578943
  spont_rate.PV1: 2.506888235294118
  spont_rate.PV2: 2.506888235294118
  spont_rate.Rorb: 3.0010052631578943
  spont_rate.Scnn1a: 3.0010052631578943
  grating_pref_rate.LIF_exc: 7.143484210526316
  grating_ortho_rate.LIF_exc: 1.428696842105263
  grating_rate.LIF_inh: 8.59714705882353
  grating_pref_rate.Nr5a1: 7.143484210526316
  grating_ortho_rate.Nr5a1: 1.428696842105263
  grating_rate.PV1: 8.59714705882353
  grating_rate.PV2: 8.59714705882353
  grating_pref_rate.Rorb: 7.143484210526316
  grating_ortho_rate.Rorb: 1.428696842105263
  grating_pref_rate.Scnn1a: 7.143484210526316
  grating_ortho_rate.Scnn1a: 1.428696842105263
x0_orig:
  weight_factor.LIF_exc.l4_i: 1.
  weight_factor.LIF_inh.l4_i: 1.
  weight_factor.Nr5a1.l4_i: 1.
  weight_factor.PV1.l4_i: 1.
  weight_factor.PV2.l4_i: 1.
  weight_factor.Rorb.l4_i: 1.
  weight_factor.Scnn1a.l4_i: 1.
  weight_factor.LIF_exc.l4_e: 1.
  weight_factor.LIF_inh.l4_e: 1.
  weight_factor.Nr5a1.l4_e: 1.
  weight_factor.PV1.l4_e: 1.
  weight_factor.PV2.l4_e: 1.
  weight_factor.Rorb.l4_e: 1.
  weight_factor.Scnn1a.l4_e: 1.
