bounds:
  weight_factor.LIF_exc.l4_i: !!python/tuple
    - 0.1
    - 10.
  weight_factor.LIF_inh.l4_i: !!python/tuple
    - 0.1
    - 10.
  weight_factor.Nr5a1.l4_i: !!python/tuple
    - 0.1
    - 10.
  weight_factor.PV1.l4_i: !!python/tuple
    - 0.1
    - 10.
  weight_factor.PV2.l4_i: !!python/tuple
    - 0.1
    - 10.
  weight_factor.Rorb.l4_i: !!python/tuple
    - 0.1
    - 10.
  weight_factor.Scnn1a.l4_i: !!python/tuple
    - 0.1
    - 10.
  weight_factor.LIF_exc.l4_e: !!python/tuple
    - 0.1
    - 10.
  weight_factor.LIF_inh.l4_e: !!python/tuple
    - 0.1
    - 10.
  weight_factor.Nr5a1.l4_e: !!python/tuple
    - 0.1
    - 10.
  weight_factor.PV1.l4_e: !!python/tuple
    - 0.1
    - 10.
  weight_factor.PV2.l4_e: !!python/tuple
    - 0.1
    - 10.
  weight_factor.Rorb.l4_e: !!python/tuple
    - 0.1
    - 10.
  weight_factor.Scnn1a.l4_e: !!python/tuple
    - 0.1
    - 10.
  weight_factor.LIF_exc.ext: !!python/tuple
    - 0.1
    - 10.
  weight_factor.LIF_inh.ext: !!python/tuple
    - 0.1
    - 10.
  weight_factor.Nr5a1.ext: !!python/tuple
    - 0.1
    - 10.
  weight_factor.PV1.ext: !!python/tuple
    - 0.1
    - 10.
  weight_factor.PV2.ext: !!python/tuple
    - 0.1
    - 10.
  weight_factor.Rorb.ext: !!python/tuple
    - 0.1
    - 10.
  weight_factor.Scnn1a.ext: !!python/tuple
    - 0.1
    - 10.
rel_bounds:
feature_names:
- spont_rate.LIF_exc
- spont_rate.LIF_inh
- spont_rate.Nr5a1
- spont_rate.PV1
- spont_rate.PV2
- spont_rate.Rorb
- spont_rate.Scnn1a
- grating_pref_rate.LIF_exc
- grating_ortho_rate.LIF_exc
- grating_rate.LIF_inh
- grating_pref_rate.Nr5a1
- grating_ortho_rate.Nr5a1
- grating_rate.PV1
- grating_rate.PV2
- grating_pref_rate.Rorb
- grating_ortho_rate.Rorb
- grating_pref_rate.Scnn1a
- grating_ortho_rate.Scnn1a
update_context:
- - optimize_L4_bionet
  - update_context
get_features_stages:
- source: optimize_L4_bionet
  compute_features: compute_features
get_objectives:
  optimize_L4_bionet: get_objectives
kwargs:
  verbose: 1
  bionet_config_file_path: config.json
  grating_angle: 0.
  pop_categories:
    l4_i:
      - LIF_inh
      - PV1
      - PV2
    l4_e:
      - LIF_exc
      - Nr5a1
      - Rorb
      - Scnn1a
    ext:
      - tw
      - lgn
objective_names:
- spont_rate.LIF_exc
- spont_rate.LIF_inh
- spont_rate.Nr5a1
- spont_rate.PV1
- spont_rate.PV2
- spont_rate.Rorb
- spont_rate.Scnn1a
- grating_pref_rate.LIF_exc
- grating_ortho_rate.LIF_exc
- grating_rate.LIF_inh
- grating_pref_rate.Nr5a1
- grating_ortho_rate.Nr5a1
- grating_rate.PV1
- grating_rate.PV2
- grating_pref_rate.Rorb
- grating_ortho_rate.Rorb
- grating_pref_rate.Scnn1a
- grating_ortho_rate.Scnn1a
optimization_title: L4_bionet
param_gen: PopulationAnnealing
param_names:
- weight_factor.LIF_exc.l4_i
- weight_factor.LIF_inh.l4_i
- weight_factor.Nr5a1.l4_i
- weight_factor.PV1.l4_i
- weight_factor.PV2.l4_i
- weight_factor.Rorb.l4_i
- weight_factor.Scnn1a.l4_i
- weight_factor.LIF_exc.l4_e
- weight_factor.LIF_inh.l4_e
- weight_factor.Nr5a1.l4_e
- weight_factor.PV1.l4_e
- weight_factor.PV2.l4_e
- weight_factor.Rorb.l4_e
- weight_factor.Scnn1a.l4_e
- weight_factor.LIF_exc.ext
- weight_factor.LIF_inh.ext
- weight_factor.Nr5a1.ext
- weight_factor.PV1.ext
- weight_factor.PV2.ext
- weight_factor.Rorb.ext
- weight_factor.Scnn1a.ext
target_range:
  spont_rate.LIF_exc: 0.1
  spont_rate.LIF_inh: 0.1
  spont_rate.Nr5a1: 0.1
  spont_rate.PV1: 0.1
  spont_rate.PV2: 0.1
  spont_rate.Rorb: 0.1
  spont_rate.Scnn1a: 0.1
  grating_pref_rate.LIF_exc: 0.1
  grating_ortho_rate.LIF_exc: 0.1
  grating_rate.LIF_inh: 0.1
  grating_pref_rate.Nr5a1: 0.1
  grating_ortho_rate.Nr5a1: 0.1
  grating_rate.PV1: 0.1
  grating_rate.PV2: 0.1
  grating_pref_rate.Rorb: 0.1
  grating_ortho_rate.Rorb: 0.1
  grating_pref_rate.Scnn1a: 0.1
  grating_ortho_rate.Scnn1a: 0.1
target_val:
  spont_rate.LIF_exc: 3.0010052631578943
  spont_rate.LIF_inh: 2.506888235294118
  spont_rate.Nr5a1: 3.0010052631578943
  spont_rate.PV1: 2.506888235294118
  spont_rate.PV2: 2.506888235294118
  spont_rate.Rorb: 3.0010052631578943
  spont_rate.Scnn1a: 3.0010052631578943
  grating_pref_rate.LIF_exc: 7.143484210526316
  grating_ortho_rate.LIF_exc: 2.3499828590277105
  grating_rate.LIF_inh: 8.59714705882353
  grating_pref_rate.Nr5a1: 7.143484210526316
  grating_ortho_rate.Nr5a1: 2.3499828590277105
  grating_rate.PV1: 8.59714705882353
  grating_rate.PV2: 8.59714705882353
  grating_pref_rate.Rorb: 7.143484210526316
  grating_ortho_rate.Rorb: 2.3499828590277105
  grating_pref_rate.Scnn1a: 7.143484210526316
  grating_ortho_rate.Scnn1a: 2.3499828590277105
x0:
  weight_factor.LIF_exc.l4_i: 1.
  weight_factor.LIF_inh.l4_i: 1.
  weight_factor.Nr5a1.l4_i: 1.
  weight_factor.PV1.l4_i: 1.
  weight_factor.PV2.l4_i: 1.
  weight_factor.Rorb.l4_i: 1.
  weight_factor.Scnn1a.l4_i: 1.
  weight_factor.LIF_exc.l4_e: 1.
  weight_factor.LIF_inh.l4_e: 1.
  weight_factor.Nr5a1.l4_e: 1.
  weight_factor.PV1.l4_e: 1.
  weight_factor.PV2.l4_e: 1.
  weight_factor.Rorb.l4_e: 1.
  weight_factor.Scnn1a.l4_e: 1.
  weight_factor.LIF_exc.ext: 1.
  weight_factor.LIF_inh.ext: 1.
  weight_factor.Nr5a1.ext: 1.
  weight_factor.PV1.ext: 1.
  weight_factor.PV2.ext: 1.
  weight_factor.Rorb.ext: 1.
  weight_factor.Scnn1a.ext: 1.
